name: Auto LineageOS Tree Generator

on:
  workflow_dispatch:
    inputs:
      DUMP_URL:
        description: 'Dump link (Git URL)'
        required: true
        default: ''
      DUMP_BRANCH:
        description: 'Dump branch (z. B. main oder master)'
        required: true
        default: ''
      DEVICE_BRAND:
        description: 'Device manufacturer (z. B. samsung)'
        required: true
        default: ''
      CODENAME:
        description: 'Device codename (z. B. a15)'
        required: true
        default: ''
      GIT_NAME:
        description: 'GitHub user name'
        required: true
        default: ''
      GIT_EMAIL:
        description: 'GitHub email'
        required: true
        default: ''

jobs:
  gen-tree:
    name: Create LineageOS-compatible tree
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.LOS_TOKEN }}
      DU: ${{ github.event.inputs.DUMP_URL }}
      DUB: ${{ github.event.inputs.DUMP_BRANCH }}
      DB: ${{ github.event.inputs.DEVICE_BRAND }}
      CN: ${{ github.event.inputs.CODENAME }}
      GN: ${{ github.event.inputs.GIT_NAME }}
      GE: ${{ github.event.inputs.GIT_EMAIL }}

    permissions:
      contents: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update && sudo apt install -y cpio python3 git curl

    - name: Install GitHub CLI
      run: |
        curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg
        sudo chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null
        sudo apt update && sudo apt install -y gh

    - name: Clone ROM Dump
      run: |
        mkdir -p "${GITHUB_WORKSPACE}/${DB}_${CN}_LOS"
        cd "${GITHUB_WORKSPACE}/${DB}_${CN}_LOS"
        git clone "${DU}" -b "${DUB}" dump

    - name: Install AOSPDTGEN
      run: pip3 install aospdtgen

    - name: Generate Device Tree
      run: |
        cd "${GITHUB_WORKSPACE}/${DB}_${CN}_LOS/dump"
        python3 -m aospdtgen .
        mv output "${GITHUB_WORKSPACE}/${DB}_${CN}_LOS/device_tree"

    - name: Setup Git identity
      run: |
        git config --global user.name "${GN}"
        git config --global user.email "${GE}"

    - name: Push to GitHub
      run: |
        cd "${GITHUB_WORKSPACE}/${DB}_${CN}_LOS/device_tree"
        git init
        git checkout -b "lineage-${CN}"
        git add .
        git commit -s -m "${CN}: initial LineageOS-compatible device tree"
        gh repo create "lineage_device_${DB}_${CN}" \
          --public \
          --description="LineageOS device tree for ${DB}/${CN}" \
          --source=. \
          --remote=origin \
          --push
        echo "✅ Erfolgreich hochgeladen: lineage_device_${DB}_${CN}"
